services:
- type: web
  name: canvas-sync-web
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --preload --bind 0.0.0.0:$PORT
  envVars:
  - key: CANVAS_BASE_URL
    sync: false
  - key: CANVAS_TOKEN
    sync: false
  - key: CANVAS_COURSE_IDS
    sync: false
  - key: SHEET_ID
    sync: false
  - key: CALENDAR_ID
    sync: false
  - key: GOOGLE_CREDENTIALS_JSON_B64
    sync: false
  - key: TZ
    value: America/Chicago

- type: cron
  name: canvas-sync-cron
  env: python
  schedule: "0 7 * * *"
  buildCommand: pip install -r requirements.txt
  startCommand: python -c "import os,requests;requests.post(f'http://{os.environ[\"SYNC_HOST\"]}:{os.environ[\"SYNC_PORT\"]}/sync', timeout=120)"
  envVars:
  - key: SYNC_HOST
    fromService:
      name: canvas-sync-web
      type: web
      property: host
  - key: SYNC_PORT
    fromService:
      name: canvas-sync-web
      type: web
      property: port
